modelname: mimic_fasttext
datapack_dir: tmp/dir
BPE: Nomore
GPU: 0
epoch: 40
character_embed_num: 20
feature_num: 200
hidden_num: 600
batchsize: 50
devsize: 1000
testsize: 1000
trainsize: 100000
compareword: 100
training_rate: 0.001
dropout: 0
use_relation: Normal
NN_model: RNN
init_emb: None
wordvector: FastText
wordvectordir: your/wordvector/dir
Objective_Function: MSE
load_train: False
overfit: False
