modelname: mimic_fasttext
datapack_dir: C:/Users/isogawa/word2vec_en/mimic/simmimic_basedatapack_fasttext_100000.pkl
BPE: Nomore
GPU: 0
epoch: 40
character_embed_num: 20
feature_num: 200
hidden_num: 600
batchsize: 50
devsize: 1000
testsize: 1000
trainsize: 100000
compareword: 100
training_rate: 0.001
dropout: 0
use_relation: Normal
NN_model: RNN
init_emb: None
wordvector: FastText
wordvectordir: D:/wiki_20180801/fastText/build/fasttext.sgns.bin
Objective_Function: MSE
load_train: False
overfit: False